# Generated by Django 3.2.5 on 2021-09-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_reply_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(default='settings.MEDIA_ROOT/uploads/sample.txt', upload_to='uploads/'),
        ),
    ]
