# Generated by Django 3.2.5 on 2021-09-19 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_post_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
